import { REGEX, CONFIG } from './constants';
import { IconFile } from '../types';

/** Tracks generated IDs within a single load session to detect collisions */
const seenIds = new Map<string, string>();

/** Call before each full icon-load pass to reset collision tracking */
export function resetIdRegistry(): void {
	seenIds.clear();
}

/**
 * Registers an ID that was reused from the cache (not freshly generated by
 * generateIconId) so later collision checks in the same pass see it. Without
 * this, a cache-hit icon's ID never enters seenIds, and a newly-added icon
 * that normalizes to the same ID goes undetected as a collision - both files
 * end up registered under one iconId, and Obsidian's addIcon() silently drops
 * one of them (last call wins).
 */
export function registerExistingId(id: string, path: string): void {
	seenIds.set(id, path);
}

export function generateIconId(icon: IconFile): string {
	const iconFileNameWithoutExtension = icon.name.substring(0, icon.name.lastIndexOf('.'));
	const base = icon.prefix ?
		`${icon.prefix}${CONFIG.ID_SEPARATOR}${iconFileNameWithoutExtension}` :
		iconFileNameWithoutExtension;

	const normalized = base
		.replace(REGEX.WHITESPACE, CONFIG.ID_SEPARATOR)
		.toLowerCase()
		.replace(REGEX.DOTS, CONFIG.ID_SEPARATOR);

	// Detect collisions: if another file already produced this ID, append a
	// short hash of the original path so both icons get unique, stable IDs.
	const existing = seenIds.get(normalized);
	if (existing && existing !== icon.path) {
		const hash = shortHash(icon.path);
		const uniqueId = `${normalized}${CONFIG.ID_SEPARATOR}${hash}`;
		seenIds.set(uniqueId, icon.path);
		return uniqueId;
	}

	seenIds.set(normalized, icon.path);
	return normalized;
}

/** Produces a short (6-char) hex hash of a string for collision disambiguation */
function shortHash(str: string): string {
	let h = 0x811c9dc5;
	for (let i = 0; i < str.length; i++) {
		h ^= str.charCodeAt(i);
		h = (h * 0x01000193) >>> 0;
	}
	return h.toString(16).slice(0, 6);
}

export function cleanFolderName(folderName: string): string {
	return folderName
		.replace(REGEX.WHITESPACE, CONFIG.ID_SEPARATOR)
		.toLowerCase();
}
